FROM openjdk:17

LABEL maintainer="tinyfingers"

WORKDIR /app

COPY target/FoodieApp-0.0.1-SNAPSHOT.jar /app/FoodieApp-0.0.1-SNAPSHOT.jar

ENV DATABASE_URL=${DATABASE_URL}
ENV DATABASE_USER=${DATABASE_USER}
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}

EXPOSE 8080

#CMD ["sh", "-cp", "java -jar -DDATABASE_URL=${DATABASE_URL} -DDATABSE_USER=${DATABASE_USER} -DDATABASE_PASSWORD=${DATABASE_PASSWORD} FoodieApp-0.0.1-SNAPSHOT.jar"]
CMD ["sh", "-cp", "java -jar FoodieApp-0.0.1-SNAPSHOT.jar"]
