version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=Foodie
      - MYSQL_USER=FoodieAdmin
      - MYSQL_PASSWORD=FoodieAdminPassword
    ports:
      - "3306:3306"
    networks:
      - foodie
networks:
  foodie:
    driver: bridge